from omegaconf import DictConfig
from dataclasses import dataclass, field
from typing import Any, Dict, List, Type
from langchain_core.messages import SystemMessage
from pydantic import BaseModel, Field, create_model

from .dimensions import Dimension, get_dimensions
from patienthub.base import EvaluatorAgent
from patienthub.configs import APIModelConfig
from patienthub.utils import load_prompts, get_chat_model


@dataclass
class StaticInterviewEvaluatorConfig(APIModelConfig):
    """Configuration for Interview Evaluator."""

    target: str = "client"
    eval_type: str = "interview"
    num_questions: int = 5


"""
    Use-cases of interview:
    1. Interview a character based on a series of pre-defined questions and evaluate the answer
    2. Interview a character based on dynamic questions generated by the model itself
"""


class InterviewEvaluator(EvaluatorAgent):
    def __init__(self, configs: DictConfig):
        self.configs = configs
        self.model = get_chat_model(configs)
        self.prompts = load_prompts(
            role="evaluator", agent_type="interview", lang=configs.lang
        )

    def init_state(self):
        """
        Need the following to do a good job:
        1. Number of questions to ask + goal of the interview
        2. Character being interviewed (profile)
        3. Previous conversation history (if any)
        """
        pass
